import type {
  CreateWeightLogInput,
  MoodRepository,
  NoteRepository,
  ReminderRepository,
  ScheduleRepository,
  TaskRepository,
  UpsertDailyTaskInput,
  UpsertWorkoutInput,
  UserRepository,
  WeightRepository,
  WorkoutRepository,
} from "@/domain/repositories";
import { getDb } from "@/lib/db";
import type { DailyTask, MoodLog, Reminder, User, WeightLog, Workout } from "@/domain";


function row<T>(v: unknown): T { return v as T; }

export const drizzleTaskRepository: TaskRepository = {
  async listByDate(userId, planDate) {
    const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } };
    const rows = await db.execute(`select t.* from daily_tasks t join daily_plans p on p.id=t.daily_plan_id where t.user_id=${userId} and p.plan_date=${planDate} order by t.sort_order asc`);
    return rows.map((r) => ({ id: row<any>(r).id, userId: row<any>(r).user_id, dailyPlanId: row<any>(r).daily_plan_id, title: row<any>(r).title, description: row<any>(r).description, status: row<any>(r).status, priority: row<any>(r).priority, sortOrder: row<any>(r).sort_order, dueAt: row<any>(r).due_at, completedAt: row<any>(r).completed_at, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at } as DailyTask));
  },
  async upsert(input: UpsertDailyTaskInput) {
    const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } };
    const [r] = await db.execute(`insert into daily_tasks (id,user_id,daily_plan_id,title,description,status,priority,sort_order,due_at,completed_at,created_at,updated_at) values (gen_random_uuid(),${input.userId},${input.dailyPlanId},${input.title},${input.description ?? null},${input.status ?? "todo"},${input.priority ?? null},${input.sortOrder ?? 0},${input.dueAt ?? null},${input.completedAt ?? null},now(),now()) returning *`);
    return { id: row<any>(r).id, userId: row<any>(r).user_id, dailyPlanId: row<any>(r).daily_plan_id, title: row<any>(r).title, description: row<any>(r).description, status: row<any>(r).status, priority: row<any>(r).priority, sortOrder: row<any>(r).sort_order, dueAt: row<any>(r).due_at, completedAt: row<any>(r).completed_at, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at };
  },
};

export const drizzleWorkoutRepository: WorkoutRepository = {
  async listUpcoming(userId) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const rows = await db.execute(`select * from workouts where user_id=${userId} order by scheduled_at asc nulls last, created_at desc`); return rows.map((r) => ({ id: row<any>(r).id, userId: row<any>(r).user_id, dailyPlanId: row<any>(r).daily_plan_id, name: row<any>(r).name, workoutType: row<any>(r).workout_type, status: row<any>(r).status, scheduledAt: row<any>(r).scheduled_at, startedAt: row<any>(r).started_at, completedAt: row<any>(r).completed_at, notes: row<any>(r).notes, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at } as Workout)); },
  async upsert(input: UpsertWorkoutInput) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`insert into workouts (id,user_id,daily_plan_id,name,workout_type,status,scheduled_at,started_at,completed_at,notes,created_at,updated_at) values (gen_random_uuid(),${input.userId},${input.dailyPlanId ?? null},${input.name},${input.workoutType ?? "mixed"},${input.status ?? "planned"},${input.scheduledAt ?? null},${input.startedAt ?? null},${input.completedAt ?? null},${input.notes ?? null},now(),now()) returning *`); return { id: row<any>(r).id, userId: row<any>(r).user_id, dailyPlanId: row<any>(r).daily_plan_id, name: row<any>(r).name, workoutType: row<any>(r).workout_type, status: row<any>(r).status, scheduledAt: row<any>(r).scheduled_at, startedAt: row<any>(r).started_at, completedAt: row<any>(r).completed_at, notes: row<any>(r).notes, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at }; },
};

export const drizzleScheduleRepository: ScheduleRepository = { async upsertPlan(input) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`insert into daily_plans (id,user_id,plan_date,status,summary,created_at,updated_at) values (gen_random_uuid(),${input.userId},${input.planDate},${input.status},${input.summary},now(),now()) on conflict (user_id,plan_date) do update set status=excluded.status, summary=excluded.summary, updated_at=now() returning *`); return { id: row<any>(r).id, userId: row<any>(r).user_id, planDate: row<any>(r).plan_date, status: row<any>(r).status, summary: row<any>(r).summary }; }, async listPlanCompletions(userId, range) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const rows = await db.execute(`select p.plan_date, coalesce(round(avg(case when t.status='completed' then 100 else 0 end)),0)::int as completion_percent from daily_plans p left join daily_tasks t on t.daily_plan_id=p.id and t.user_id=p.user_id where p.user_id=${userId} and p.plan_date between ${range.from} and ${range.to} group by p.plan_date order by p.plan_date asc`); return rows.map((r) => ({ planDate: row<any>(r).plan_date, completionPercent: row<any>(r).completion_percent })); } };

export const drizzleWeightRepository: WeightRepository = { async create(input: CreateWeightLogInput) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`insert into weight_logs (id,user_id,logged_on,logged_at,weight_value,weight_unit,source,notes,created_at,updated_at) values (gen_random_uuid(),${input.userId},${input.loggedOn},${input.loggedAt ?? null},${input.weightValue},${input.weightUnit ?? "lb"},${input.source ?? "manual"},${input.notes ?? null},now(),now()) returning *`); return { id: row<any>(r).id, userId: row<any>(r).user_id, loggedOn: row<any>(r).logged_on, loggedAt: row<any>(r).logged_at, weightValue: row<any>(r).weight_value, weightUnit: row<any>(r).weight_unit, source: row<any>(r).source, notes: row<any>(r).notes, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at } as WeightLog; } };
export const drizzleNoteRepository: NoteRepository = { async create(input) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`insert into daily_notes (id,user_id,daily_plan_id,content,created_at,updated_at) values (gen_random_uuid(),${input.userId},${input.dailyPlanId},${input.content},now(),now()) returning *`); return { id: row<any>(r).id, userId: row<any>(r).user_id, dailyPlanId: row<any>(r).daily_plan_id, content: row<any>(r).content }; } };
export const drizzleMoodRepository: MoodRepository = { async create(input) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`insert into mood_logs (id,user_id,logged_on,mood_score,notes,created_at,updated_at) values (gen_random_uuid(),${input.userId},${input.loggedOn},${input.moodScore},${input.notes ?? null},now(),now()) returning *`); return { id: row<any>(r).id, userId: row<any>(r).user_id, loggedOn: row<any>(r).logged_on, moodScore: row<any>(r).mood_score, notes: row<any>(r).notes, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at } as MoodLog; } };
export const drizzleReminderRepository: ReminderRepository = { async create(input) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`insert into reminders (id,user_id,daily_plan_id,related_type,related_id,category,status,channel,scheduled_at,created_at,updated_at) values (gen_random_uuid(),${input.userId},${input.dailyPlanId ?? null},${input.relatedType ?? null},${input.relatedId ?? null},${input.category},${input.status ?? "scheduled"},${input.channel ?? "in_app"},${input.scheduledAt},now(),now()) returning *`); return { id: row<any>(r).id, userId: row<any>(r).user_id, dailyPlanId: row<any>(r).daily_plan_id, relatedType: row<any>(r).related_type, relatedId: row<any>(r).related_id, category: row<any>(r).category, status: row<any>(r).status, channel: row<any>(r).channel, scheduledAt: row<any>(r).scheduled_at, deliveredAt: row<any>(r).delivered_at, snoozedUntil: row<any>(r).snoozed_until, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at } as Reminder; } };
export const drizzleUserRepository: UserRepository = { async getById(id) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`select * from users where id=${id} limit 1`); if (!r) return null; return { id: row<any>(r).id, displayName: row<any>(r).display_name, email: row<any>(r).email, timezone: row<any>(r).timezone, unitSystem: row<any>(r).unit_system, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at } as User; }, async create(input) { const { db } = getDb() as { db: { execute: (q: unknown) => Promise<unknown[]> } }; const [r] = await db.execute(`insert into users (id,display_name,email,timezone,unit_system,created_at,updated_at) values (${input.id ?? "gen_random_uuid()"},${input.displayName ?? null},${input.email ?? null},${input.timezone ?? "UTC"},${input.unitSystem ?? "imperial"},now(),now()) returning *`); return { id: row<any>(r).id, displayName: row<any>(r).display_name, email: row<any>(r).email, timezone: row<any>(r).timezone, unitSystem: row<any>(r).unit_system, createdAt: row<any>(r).created_at, updatedAt: row<any>(r).updated_at } as User; } };
